analysis:
  analysis_raw_dir: /data/scratch/prince.xavier/SALMON/raw_data/analysis/analysis_bucket
  analysis_moose_dir: moose:/opfc/atm/global/prods/
  analysis_dummy_queryfiles_dir: /data/scratch/prince.xavier/SALMON/temp
  analysis_combined_queryfile: /home/users/prince.xavier/MJO/SALMON/RETRIEVALS/analysis_combined.query
  mjo:
    analysis_mjo_processed_dir: /data/scratch/prince.xavier/SALMON/processed_SEA_data/analysis/mjo/
    analysis_mjo_rmm_archive_dir: /data/users/prince.xavier/SALMON/processed_SEA_data/analysis/mjo/rmms/
  eqwaves:
    analysis_eqwaves_processed_dir: /data/scratch/prince.xavier/SALMON/processed_SEA_data/analysis/eqwaves

mogreps:
  mogreps_dummy_queryfiles_dir: /data/scratch/prince.xavier/SALMON/temp
  mogreps_moose_dir: moose:/opfc/atm/mogreps-g/prods/
  mogreps_raw_dir: /data/scratch/prince.xavier/SALMON/raw_data/mogreps/mogreps_bucket
  mogreps_combined_queryfile: /home/users/prince.xavier/MJO/SALMON/RETRIEVALS/mogreps_combined.query
  mjo:
    mogreps_mjo_processed_dir: /data/scratch/prince.xavier/SALMON/processed_SEA_data/mogreps/mjo
    mogreps_mjo_archive_dir: /data/users/prince.xavier/SALMON/processed_SEA_data/mogreps/mjo/rmms/
    mogreps_mjo_plot_ens: /data/users/prince.xavier/SALMON/processed_SEA_data/mogreps/mjo/plot_ens/
  cs:
    mogreps_cs_processed_dir: /data/scratch/prince.xavier/SALMON/processed_SEA_data/mogreps/coldsurge/
    mogreps_cs_plot_ens: /data/users/prince.xavier/SALMON/processed_SEA_data/mogreps/coldsurge/plot_ens/
  eqwaves:
    mogreps_eqwaves_processed_dir: /data/scratch/prince.xavier/SALMON/processed_SEA_data/mogreps/eqwaves/
    mogreps_eqwaves_plot_ens: /data/users/prince.xavier/SALMON/processed_SEA_data/mogreps/eqwaves/plot_ens/
  indices:
    mogreps_indices_processed_dir: /data/scratch/prince.xavier/SALMON/processed_SEA_data/mogreps/indices/
    mogreps_indices_plot_ens: /data/users/prince.xavier/SALMON/processed_SEA_data/mogreps/indices/plot_ens/
  #bsiso:
  #  mogreps_bsiso_processed_dir: /data/scratch/prince.xavier/SEA_monitoring/processed_SEA_data/mogreps/MJO
  #  mogreps_bsiso_archive_dir: /project/MJO_GCSS/SEA_monitoring/processed_BSISO_data/mogreps/bsiso_new/
  #  mogreps_bsiso_plot_ens: /project/MJO_GCSS/SEA_monitoring/processed_BSISO_data/mogreps/plot_ens_new

glosea:
  glosea_dummy_queryfiles_dir: /data/scratch/prince.xavier/SALMON/temp
  glosea_combined_queryfile: /home/users/prince.xavier/MJO/Monitoring_new/RETRIEVALS/glosea_combined.query
  glosea_raw_dir: /data/scratch/prince.xavier/SALMON/raw_data/glosea/glosea_bucket
  mjo:
    glosea_mjo_processed_dir: /data/scratch/prince.xavier/SALMON/processed_SEA_data/glosea/mjo
    glosea_mjo_archive_dir: /data/users/prince.xavier/SALMON/processed_SEA_data/glosea/mjo/rmms/
    glosea_mjo_plot_ens: /data/users/prince.xavier/SALMON/processed_SEA_data/glosea/mjo/plot_ens/
  cs:
    glosea_cs_processed_dir: /data/scratch/prince.xavier/SALMON/processed_SEA_data/glosea/coldsurge
    glosea_cs_plot_ens: /data/users/prince.xavier/SALMON/processed_SEA_data/glosea/plot_ens_new
  #bsiso:
  #  glosea_bsiso_processed_dir: /data/scratch/prince.xavier/SEA_monitoring/processed_SEA_data/glosea/MJO
  #  glosea_bsiso_archive_dir: /project/MJO_GCSS/SEA_monitoring/processed_BSISO_data/glosea/bsiso_new/
  #  glosea_bsiso_plot_ens: /project/MJO_GCSS/SEA_monitoring/processed_BSISO_data/glosea/plot_ens_new
