analysis:
  raw: $SCRATCH/SALMON/raw_data/analysis/analysis_bucket
  moose: moose:/opfc/atm/global/prods/
  temp: $SCRATCH/SALMON/temp
  query: $HOME/MJO/SALMON/RETRIEVALS/analysis_combined.query
  processed: $SCRATCH/SALMON/processed_SEA_data/analysis
  archive: $DATA/SALMON/processed_SEA_data/analysis
  plots: $DATA/SALMON/processed_SEA_data/analysis

mogreps:
  raw: $SCRATCH/SALMON/raw_data/mogreps/mogreps_bucket
  moose: moose:/opfc/atm/mogreps-g/prods/
  temp: $SCRATCH/SALMON/temp
  query: $HOME/MJO/SALMON/RETRIEVALS/mogreps_combined.query
  processed: $SCRATCH/SALMON/processed_SEA_data/mogreps
  archive: $DATA/SALMON/processed_SEA_data/mogreps
  plots: $DATA/SALMON/processed_SEA_data/mogreps

glosea:
  raw: $SCRATCH/SALMON/raw_data/glosea/glosea_bucket
  moose: moose:/opfc/atm/glosea/prods/
  processed: $SCRATCH/SALMON/processed_SEA_data/glosea
  archive: $DATA/SALMON/processed_SEA_data/glosea
  plots: $DATA/SALMON/processed_SEA_data/glosea

global:
  forecast_out_dir: $SCRATCH/SALMON/processed_SEA_data/mogreps
